import type { Metadata } from "next";
import { Noto_Sans_KR, Space_Grotesk } from "next/font/google";
import "./css/reset.scss";
import "./css/globals.scss";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import Providers from "./Provider";

const bodyFont = Noto_Sans_KR({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

const displayFont = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Open Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.variable} ${displayFont.variable} antialiased`}
      >
        <header>
          <div className="container">
            <div className="header-inner">
              <div className="left">
                <h1>
                  <Link href={'/'}>
                    Open Quiz
                  </Link>
                </h1>
                <Link href={'/'}>
                  퀴즈 목록
                </Link>
                <Link href={'/add_quiz'}>
                  퀴즈 만들기
                </Link>
              </div>
              <div className="right">
                <Providers>
                  <LoginBtn></LoginBtn>
                </Providers>
              </div>
            </div>
          </div>
        </header>
        {children}

        <div className="footer">
          <div className="container">
            <div className="footer-wrap">
              <p className="exp">
                본 웹사이트는 김정민의 개인 프로젝트 목적으로 제작되었습니다. 
                카카오 계정의 개인 식별값 외에는 개인정보를 수집하지 않으며, 
                사이트는 언제든지 폐쇄될 수 있고 자료가 삭제될 수 있습니다.
              </p>
              <p className="copyright">© 2026 김정민. All rights reserved.</p>
            </div>
          </div>
        </div>



        
      </body>
    </html>
  );
}
