import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/reset.scss";
import "./css/globals.scss";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import Providers from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="container">
            <div className="header-inner">
              <div className="left">
                <h1>
                  <Link href={'/'}>
                    Open Quiz
                  </Link>
                </h1>
                <Link href={'/'}>
                  퀴즈 목록
                </Link>
                <Link href={'/add_quiz'}>
                  퀴즈 만들기
                </Link>
              </div>
              <div className="right">
                <Providers>
                  <LoginBtn></LoginBtn>
                </Providers>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
